name: Build & Release Showroom

on:
  push:
    tags:
      - 'v*' # Execute only when a tag like v1.0.0 is present

jobs:
  export:
    name: Export & Release Godot Project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup & Export with Godot 4
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_file_subpath: 'godot'
          godot_headless_file_subpath: 'godot'
          godot_version: '4.6.1'
          godot_channel: 'stable'
          export_debug: false
          archive_output: true
          relative_project_path: './'

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/Windows.zip
            build/Linux.zip
            build/macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}